package modelo;
// Generated 17-11-2020 11:48:38 by Hibernate Tools 4.3.1



/**
 * DetallePedido generated by hbm2java
 */
public class DetallePedido  implements java.io.Serializable {


     private Integer idDetalle;
     private Pedido pedido;
     private Producto producto;
     private int cantidad;
     private int subtotal;

    public DetallePedido() {
    }

    public DetallePedido(Pedido pedido, Producto producto, int cantidad, int subtotal) {
       this.pedido = pedido;
       this.producto = producto;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
    }
   
    public Integer getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(Integer idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public int getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(int subtotal) {
        this.subtotal = subtotal;
    }




}


