package modelo;
// Generated 17-11-2020 11:48:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MetodoPago generated by hbm2java
 */
public class MetodoPago  implements java.io.Serializable {


     private Integer idMetodo;
     private String descripcion;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public MetodoPago() {
    }

	
    public MetodoPago(String descripcion) {
        this.descripcion = descripcion;
    }
    public MetodoPago(String descripcion, Set<Pedido> pedidos) {
       this.descripcion = descripcion;
       this.pedidos = pedidos;
    }
   
    public Integer getIdMetodo() {
        return this.idMetodo;
    }
    
    public void setIdMetodo(Integer idMetodo) {
        this.idMetodo = idMetodo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


