package modelo;
// Generated 17-11-2020 11:48:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Categoria categoria;
     private PuntoVenta puntoVenta;
     private String nombre;
     private int precio;
     private String imagen;
     private boolean activo;
     private Set<DetallePedido> detallePedidos = new HashSet<DetallePedido>(0);

    public Producto() {
    }

	
    public Producto(Categoria categoria, PuntoVenta puntoVenta, String nombre, int precio, String imagen, boolean activo) {
        this.categoria = categoria;
        this.puntoVenta = puntoVenta;
        this.nombre = nombre;
        this.precio = precio;
        this.imagen = imagen;
        this.activo = activo;
    }
    public Producto(Categoria categoria, PuntoVenta puntoVenta, String nombre, int precio, String imagen, boolean activo, Set<DetallePedido> detallePedidos) {
       this.categoria = categoria;
       this.puntoVenta = puntoVenta;
       this.nombre = nombre;
       this.precio = precio;
       this.imagen = imagen;
       this.activo = activo;
       this.detallePedidos = detallePedidos;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public PuntoVenta getPuntoVenta() {
        return this.puntoVenta;
    }
    
    public void setPuntoVenta(PuntoVenta puntoVenta) {
        this.puntoVenta = puntoVenta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<DetallePedido> getDetallePedidos() {
        return this.detallePedidos;
    }
    
    public void setDetallePedidos(Set<DetallePedido> detallePedidos) {
        this.detallePedidos = detallePedidos;
    }




}


