package modelo;
// Generated 17-11-2020 11:48:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoEntrega generated by hbm2java
 */
public class TipoEntrega  implements java.io.Serializable {


     private Integer idTipoEntrega;
     private String descripcion;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public TipoEntrega() {
    }

	
    public TipoEntrega(String descripcion) {
        this.descripcion = descripcion;
    }
    public TipoEntrega(String descripcion, Set<Pedido> pedidos) {
       this.descripcion = descripcion;
       this.pedidos = pedidos;
    }
   
    public Integer getIdTipoEntrega() {
        return this.idTipoEntrega;
    }
    
    public void setIdTipoEntrega(Integer idTipoEntrega) {
        this.idTipoEntrega = idTipoEntrega;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


