package modelo;
// Generated 17-11-2020 11:48:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ubicacion generated by hbm2java
 */
public class Ubicacion  implements java.io.Serializable {


     private Integer idUbicacion;
     private Sede sede;
     private String nombreEdificio;
     private String piso;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Ubicacion() {
    }

	
    public Ubicacion(Sede sede, String nombreEdificio, String piso) {
        this.sede = sede;
        this.nombreEdificio = nombreEdificio;
        this.piso = piso;
    }
    public Ubicacion(Sede sede, String nombreEdificio, String piso, Set<Pedido> pedidos) {
       this.sede = sede;
       this.nombreEdificio = nombreEdificio;
       this.piso = piso;
       this.pedidos = pedidos;
    }
   
    public Integer getIdUbicacion() {
        return this.idUbicacion;
    }
    
    public void setIdUbicacion(Integer idUbicacion) {
        this.idUbicacion = idUbicacion;
    }
    public Sede getSede() {
        return this.sede;
    }
    
    public void setSede(Sede sede) {
        this.sede = sede;
    }
    public String getNombreEdificio() {
        return this.nombreEdificio;
    }
    
    public void setNombreEdificio(String nombreEdificio) {
        this.nombreEdificio = nombreEdificio;
    }
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


