package modelo;
// Generated 17-11-2020 11:48:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;


/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private PuntoVenta puntoVenta;
     private Sede sede;
     private TipoUsuario tipoUsuario;
     private String rut;
     private String nombre;
     private String apellido;
     private String email;
     private Integer telefono;
     private String contrasena;
     private boolean activo;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Usuario() {
    }

   
    public Usuario(TipoUsuario tipoUsuario, String rut, String nombre, String apellido, String email, String contrasena, boolean activo) {
        this.tipoUsuario = tipoUsuario;
        this.rut = rut;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.contrasena = contrasena;
        this.activo = activo;
    }
    public Usuario(PuntoVenta puntoVenta, Sede sede, TipoUsuario tipoUsuario, String rut, String nombre, String apellido, String email, Integer telefono, String contrasena, boolean activo, Set<Pedido> pedidos) {
       this.puntoVenta = puntoVenta;
       this.sede = sede;
       this.tipoUsuario = tipoUsuario;
       this.rut = rut;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.telefono = telefono;
       this.contrasena = contrasena;
       this.activo = activo;
       this.pedidos = pedidos;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public PuntoVenta getPuntoVenta() {
        return this.puntoVenta;
    }
    
    public void setPuntoVenta(PuntoVenta puntoVenta) {
        this.puntoVenta = puntoVenta;
    }
    public Sede getSede() {
        return this.sede;
    }
    
    public void setSede(Sede sede) {
        this.sede = sede;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


